### ISSUE TITLE
Solved - Issue regarding expiration date assigned on overwrite

### ISSUE THREAD

**Issue by SBurwash** [z3z1ma/target-bigquery#55]
# What was happening

When using the `overwrite` feature, we were experiencing issues where tables would be assigned an expiration of 24h.
![image](https://github.com/z3z1ma/target-bigquery/assets/35510512/5efb7416-7d1b-4a7b-8393-277b7144b7e5)
![image](https://github.com/z3z1ma/target-bigquery/assets/35510512/532f9ebd-db5c-41e1-9eaa-9a8341d48d0c)

# To replicate
Running target with these parameters:
```
      denormalized: false
      method: batch_job
      timeout: 300
      batch_size: 250000
      append_columns: true
      generate_view: false
      overwrite: true
      fix_columns:
        lower: False
        quotes: False
        add_underscore_when_invalid: True
```

# How was this solved
Patch by @z3z1ma 

# Link to full conversation history:
https://meltano.slack.com/archives/C01TCRBBJD7/p1686245080714989
