### ISSUE TITLE
Schema evolution error when `denormalized` and `snake_case` is enabled

### ISSUE THREAD

**Issue by qgab-flowdesk** [z3z1ma/target-bigquery#66]
I'm running into issues to load data with the denormalised parameter enabled. 
Looking [into the code](https://github.com/z3z1ma/target-bigquery/blob/3952428bb043d1db80250e1f11cbcad9c8b18ecd/target_bigquery/core.py#L565C1-L569C14), it seems that even when the table does not yet exists in BigQuery, we run into the following error:

```sh
google.api_core.exceptions.BadRequest: 400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/project-id/datasets/salesforce/tables/campaign?prettyPrint=false: Field id already exists in schema
```

The table schema is properly defined in BigQuery, but when it comes to load the actual data it looks like the table schema if not resolved correctly. The issue persists with both version 1 and 2 of the `schema_resolver`. Maybe there is an issue with the [schema_translator](https://github.com/z3z1ma/target-bigquery/blob/3952428bb043d1db80250e1f11cbcad9c8b18ecd/target_bigquery/core.py#L99)?

If someone has Salesforce credentials, here is the corresponding Meltano configuration for reproducing the issue:

```yaml
    plugins:
    
      extractors:
      - name: tap-salesforce
        config:
          api_type: REST
          start_date: '2023-06-01T00:00:00Z'
        select:
        - Campaign.*

      loaders:
      - name: target-bigquery
        variant: z3z1ma
        config:
          project: project-id
          dataset: salesforce
          method: batch_job
          location: us-west1
          batch_size: 500
          fail_fast: True
          append: False
          overwrite: True
          flattening_enabled: True
          denormalized: True
          schema_resolver_version: 2
          column_name_transforms:
            lower: True
            quote: False
            add_underscore_when_invalid: True
            snake_case: True
```

And the `meltano` commands:

```sh
meltano --log-level=debug invoke tap-salesforce > output.json
cat output.json | meltano --log-level=debug invoke target-bigquery
```
