### ISSUE TITLE
gRPC fails to load data using `storage_write_api`

### ISSUE THREAD

**Issue by rubenvereecken** [z3z1ma/target-bigquery#76]
Specifically, using `TARGET_BIGQUERY_DEBUG=true`, I get the error:

```
google.api_core.exceptions.NotFound: 404 Requested entity was not found. Entity: projects/summitsift/datasets/test_data/tables/users/streams/_default
```

I don't know how gRPC works well enough to investigate this error. Looking at BigQuery, the dataset `summitsift.test_data` is created correctly, and it contains a table `users` with the correct schema.

What I _can_ say is that 
- it's a custom tap, though loader`target-jsonl` works just fine 
- `tap-carbon-intensity` works fine _most of the time_ with the same config (I can't reproduce it now)

`meltano.yml`:

```
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      credentials_path: ${credentials}
      dataset: test_data
      denormalized: true
      fail_fast: true
      flattening_enabled: false
      location: europe-west1
      project: ${project}
      column_name_transforms:
        snake_case: true
        add_underscore_when_invalid: true
```
