### ISSUE TITLE
Error logs when inserting data into bigquery tables

### ISSUE THREAD

**Issue by blancaruano** [z3z1ma/target-bigquery#83]
When I run meltano with tap-intercom target-bigquery, it extracts and loads the data correctly to BQ. However, in the logs I see an error for every batch that says that dataset and tables already exist in BQ. Is there any way to deactivate these logs? Or set them as info instead of error because the process works correctly.
The methods that fail are: `datasetservice.insert` and `tableservice.insert`. The logs say: `Already Exists: Dataset x` `Already Exists: Table x`
Maybe I am missing something in the setup?

This is my setup:
```
- name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      method: batch_job
      location: EU
      add_metadata_columns: true
      flattening_enabled: false
      partition_granularity: day
      batch_size: 1000
      column_name_transforms:
        snake_case: true
      overwrite: true
```
