### ISSUE TITLE
Match PyPi to github releases

### ISSUE THREAD

**Issue by AlejandroUPC** [z3z1ma/target-bigquery#92]
## Description

As of right now the github repo points to the most recent release `0.7.2` but the release history [still points](https://pypi.org/project/z3-target-bigquery/#history) to `0.6.8`.

This can lead into confusions thinking that you are using the latest relaese while you are using the last PyPi published packaged, or crash when defining the configuration in Meltano this way:

```yaml
  - name: target-bigquery
    variant: z3z1ma
    pip_url: z3-target-bigquery==0.7.2
```

Ideally we can keep the gh releases and pypi packaged synced, happy to help.
